### ISSUE TITLE
Adapter startet nicht

### ISSUE THREAD

**Issue by Thomas4170** [iobroker-community-adapters/ioBroker.oekofen-json#16]
ich habe diese Woche auch meine Ökofen Condens zeroflame bekommen und mich über die Integration in ioBroker gefreut. Ich habe die aktuellste Version des Adapters installiert und nach Anweisung die Werte eingetragen. Leider wird der Adapter nicht grün. Version des Touch-Reglers V4.01

Port war Standard 502 aber ich habe auch 8080 versucht.
Folgende Einträge stehen im Log 

`[initialScan_axios.get.catch] Error: connect ECONNREFUSED 192.168.178.30:502 - Adapter exiting now.`
`starting. Version 0.2.4 (non-npm: chaozmc/ioBroker.oekofen-json#2080cded90af466608f4cec9cdf9ba82cc2dda5d) in /opt/iobroker/node_modules/iobroker.oekofen-json, node: v16.18.0, js-controller: 4.0.23`

Vielleicht kannst Dumir ja helfen

VG Thomas

**Comment by redjudge13** [comment]
Hallo Thomas,
ich glaube du verwechselst ModBus mit JSON.
Modbus läuft auf dem Port 502, dafür ist dieser Adapter nicht geschrieben.
Dieser lädt per JSON die Daten vom Condens, das kommt unterhalb der Modbus Konfig, bei IP-Settings. Dort ist ein Port einzustellen, Standard wäre 4321, ein Passwort ist auch hinterlegt und kann geändert werden. 
Die IP (bei dir also 192.168.178.30:4321) und das Passwort von JSON aus dem Condens eintragen und nochmal probieren.

**Comment by Thomas4170** [comment]
Vielen Dank für die info, so weit runter hatte ich nicht gescrollt und wusste auch nicht das es diesen Punkt gibt.
Funktioniert und bekomme auch die Werte von Smart-PV

VG Thomas

**Comment by redjudge13** [comment]
Das freut mich, beobachte mal bitte wie lange das funktioniert, bei mir sperrt der Condens nach ein paar Stunden die Abfrage.
Hole jetzt per Oekofen-spy alle 4 Minuten mittels dem Phython Script und lege es in Influx ab.
Wenn ich nur wüsste wie ich die Daten aus Influx in den IoBroker bekomme…

**Comment by Thomas4170** [comment]
ok beobachte ich mal. ich habe keine Ahnung ob das überhaupt geht Werte aus influx in ioBroker zu schreiben. Google gibt auch nichts her

**Comment by Thomas4170** [comment]
Also bei mir läuft es bis jetzt ohne Probleme, ich habe allerdings das Intervall auf 60 sec. gesetzt. Gibt es keine Möglichkeit in dem Skript MQTT mit zu integrieren?

**Comment by Thomas4170** [comment]
Ich habe was gefunden wie Werte aus Influx in ioBroker geschrieben werden können. Schau hier mal
[https://github.com/ioBroker/ioBroker.influxdb#custom-queries ](url)

**Comment by redjudge13** [comment]
Also der Adapter läuft wunderbar, mein Fehler war eher im LAN verhortet. Danke an den Entwickler.
