### ISSUE TITLE
Error: extensible object creation in case of wrong password

### ISSUE THREAD

**Issue by looxer01** [iobroker-community-adapters/ioBroker.oekofen-json#18]
I am coming from version 0.2 and tried to upgrade to version 1.0 and received the below errors.

`<html>
<body>

host.RR-DEB-iOB | 2023-01-20 11:29:25.381 | error | Caught by controller[0]: }
-- | -- | -- | --
host.RR-DEB-iOB | 2023-01-20 11:29:25.381 | error | Caught by controller[0]: ]
host.RR-DEB-iOB | 2023-01-20 11:29:25.381 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.oekofen-json/main.js'
host.RR-DEB-iOB | 2023-01-20 11:29:25.381 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.oekofen-json/node_modules/axios/index.js',
host.RR-DEB-iOB | 2023-01-20 11:29:25.380 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.oekofen-json/node_modules/axios/lib/axios.js',
host.RR-DEB-iOB | 2023-01-20 11:29:25.380 | error | Caught by controller[0]: requireStack: [
host.RR-DEB-iOB | 2023-01-20 11:29:25.380 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.RR-DEB-iOB | 2023-01-20 11:29:25.380 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1067:19) {
host.RR-DEB-iOB | 2023-01-20 11:29:25.380 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:878:12)
host.RR-DEB-iOB | 2023-01-20 11:29:25.380 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1043:32)
host.RR-DEB-iOB | 2023-01-20 11:29:25.380 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
host.RR-DEB-iOB | 2023-01-20 11:29:25.379 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1165:14)
host.RR-DEB-iOB | 2023-01-20 11:29:25.379 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.oekofen-json/node_modules/axios/lib/axios.js:3:13)
host.RR-DEB-iOB | 2023-01-20 11:29:25.379 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:103:18)
host.RR-DEB-iOB | 2023-01-20 11:29:25.379 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1067:19)
host.RR-DEB-iOB | 2023-01-20 11:29:25.379 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:841:27)
host.RR-DEB-iOB | 2023-01-20 11:29:25.379 | error | Caught by controller[0]: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
host.RR-DEB-iOB | 2023-01-20 11:29:25.379 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.oekofen-json/main.js
host.RR-DEB-iOB | 2023-01-20 11:29:25.379 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.oekofen-json/node_modules/axios/index.js
host.RR-DEB-iOB | 2023-01-20 11:29:25.378 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.oekofen-json/node_modules/axios/lib/axios.js
host.RR-DEB-iOB | 2023-01-20 11:29:25.378 | error | Caught by controller[0]: Require stack:
host.RR-DEB-iOB | 2023-01-20 11:29:25.378 | error | Caught by controller[0]: Error: Cannot find module './utils'
host.RR-DEB-iOB | 2023-01-20 11:29:25.378 | error | Caught by controller[0]: ^
host.RR-DEB-iOB | 2023-01-20 11:29:25.378 | error | Caught by controller[0]: throw err;
host.RR-DEB-iOB | 2023-01-20 11:29:25.377 | error | Caught by controller[0]: node:internal/modules/cjs/loader:998

</body>
</html>`

**Comment by chaozmc** [comment]
hi @looxer01, which version 0.2? 0.2.0? 
In that case you most probably need to delete the instance and the adapter and start with a fresh install of 1.0.0 again. 
The commit from Aug 15, 2022 (v0.2.3) right after 0.2.0 targeted many things Apollon pointed out which have to be changed for the adapter to be compliant (encrypted passwords, static objects not created in the code, ...) so most probably this was a breaking change at the package.

**Comment by looxer01** [comment]
thx for the fast response. I completely deleted the version and then installed V1.0.
there is no error but I am getting a huge number of channels in the objects list and the system slows down of course.
looks like an error to me. Before it was like HK1, Hk2 etc which made sense to me

![oekoefen](https://user-images.githubusercontent.com/11609655/213689340-c799127e-5262-4d51-89a6-a5006046f698.JPG)

**Comment by chaozmc** [comment]
this is mostly weird tbh. You're the second one with that issue, like #7 - but i've never heard something again about it. I still can't imagine how this condition happens as there's no counter used in the code, only the response of the ökofen is parsed and iterated so in theory when i think about the process only when the response from axios contains that, this would be created. Can you normally access the json interface of your ökofen via a browser and receive a normal json response with hk1, hk2, ww1, pe1, ..?

**Comment by looxer01** [comment]
Hi,
the jason response is as expected. It worked with 0.2.0 Beta without issue.
Anthing I can do for further analysis ?

**Comment by looxer01** [comment]
Hi,
Think I have it now fixed. Seems to be a password issue. I used the password which is the one I am logging in. 
Required is the password which only can be found in the pelletronic touch display under the point ip config. 
Obviously there is an issue in cases where another password is used. Then the adapter creates 1000ends of channels.
At the moment it seems that the issue is fixed for me.

I am leaving the issue open as it seems to me a bug in cases of wrong passwords.

**Comment by chaozmc** [comment]
Hi, thats interesting news - i've never tried using a wrong password... if that is causing that behaviour maybe i can catch that in the code. i'll have a look into that
