### ISSUE TITLE
Please update test-and-release node version to node 16 / 18 / 20

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.oekofen-json#19]
You just removed node 12 from testing. Thats OK.

Please consider too:

-) removing node 14 as node 14 is end-of-life and upcoming js-controller 5will no longer support node 14. tests will fail when js-controlelr get default for testing.

-) add node 18 and node 20 to testing as node 16 will be end-of-life ende 2023, node 18 is current up to date release and many users already upgrade to node 18. 
Node 20 should be tested already as there are no known restrictions adn early detection of potenzial problems is desired. Feel free to omit node 20 if tehre are problems detected until you have time to analyze / fix them.

Thanks
McM

**Comment by mcm1957** [comment]
If not yet changes still relevant

**Comment by mcm1957** [comment]
If not yet changes still relevant

**Comment by mcm1957** [comment]
If not yet changed still todo

**Comment by mcm1957** [comment]
If not yet done still relevant

**Comment by chaozmc** [comment]
Done with V1.0.4
