### ISSUE TITLE
Problem with getting started und connect the Pelletronic Touch with Adapter

### ISSUE THREAD

**Issue by Hoss0305** [iobroker-community-adapters/ioBroker.oekofen-json#20]
Hello,
I'm having trouble setting up the adapter. The Pelletronic Touch firmware is version 4.00b. The adapter reports that it cannot connect to the device. To set it up, the IP, TCP port, the "so-called" password and the interval are required in the adapter. Which exact data is involved, which is to be specified.
The IP is probably the network IP of the Pelletronic Touch in the local network, I'm not sure about the TCP port. A JSON port is displayed in the Pelletronic Touch. Is this the correct port? Even with the "so-called" password, I don't know which one to use. Is it the JSON password that is displayed in the Pelletronic Touch menu? I have already tried the values displayed by the Pelletronic Touch, but I do not see a connection to the device. It would be great if I could get support here.

Best regards Hoss

**Comment by Hoss0305** [comment]
Hello,
I don't know why, but the connection works now. I used the local network IP, the specified JSON port and JSON password and the data came in.

Best regards Hoss

**Comment by redjudge13** [comment]
@Hoss0305 
Thank you for your feedback, I was looking for your problem, now.
Because @chaozmc did a great job and helped me, so I have to give it back!
Nice sunday

btw: Why do you have the 4.00b, there is minimum the 4.02...
