### ISSUE TITLE
Add datapoint name

### ISSUE THREAD

**Issue by ScumbagSteve** [iobroker-community-adapters/ioBroker.oekofen-json#24]
I have just replaced my own coding with your adapter and noticed the datapoints are missing an understandable name (e.g.hk1.L_flowtemp_set = Vorlauftemperatur Soll).
If you consider integrating this, let me know which format you require and I could contribute the naming in german for you, to support this project.

Thanks for the adapter

**Comment by chaozmc** [comment]
Hi,

I thought it's anyhow clear what data point is referring to. Anyway if you would like to add that, feel free! I guess the correct way to implement this would be with an separate file in json format which then can get translated to all other languages automatically too?

**Comment by ScumbagSteve** [comment]
I agree, I guess that's the best approach. 
If you send me over the structure of the file, I can provide it.
