### ISSUE TITLE
Falsch angelegte Objekte

### ISSUE THREAD

**Issue by HJS72** [iobroker-community-adapters/ioBroker.oekofen-json#7]
Hallo,
hab gerade die aktuelle Version zum Test installiert. Leider legt mir die Instanz nur Objekte mit laufender Nummer an (1600 Stück).
Im Logfile erhalte ich folgende Infos:

`oekofen-json.0 | 2022-07-15 21:25:31.211 | warn | State "oekofen-json.0.weather.L_forecast_clouds" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
oekofen-json.0 | 2022-07-15 21:25:31.210 | warn | State "oekofen-json.0.weather.L_forecast_temp" has no existing object, this might lead to an error in future versions
oekofen-json.0 | 2022-07-15 21:25:31.209 | warn | State "oekofen-json.0.weather.L_clouds" has no existing object, this might lead to an error in future versions
oekofen-json.0 | 2022-07-15 21:25:31.209 | warn | State "oekofen-json.0.weather.L_temp" has no existing object, this might lead to an error in future versions
oekofen-json.0 | 2022-07-15 21:25:31.208 | warn | State "oekofen-json.0.system.L_usb_stick" has no existing object, this might lead to an error in future versions
oekofen-json.0 | 2022-07-15 21:25:31.207 | warn | State "oekofen-json.0.system.L_errors" has no existing object, this might lead to an error in future versions
oekofen-json.0 | 2022-07-15 21:25:31.173 | warn | State "oekofen-json.0.system.L_ambient" has no existing object, this might lead to an error in future versions
oekofen-json.0 | 2022-07-15 21:25:31.064 | debug | [updateData_axios.get] set info.connection to true as request was successful
oekofen-json.0 | 2022-07-15 21:25:31.059 | debug | [updateData_axios.get] got HTTP/200 response, call parseDataAndSetValues with response.data
oekofen-json.0 | 2022-07-15 21:25:30.559 | debug | [updateData] called with url: http://192.168.10.110:4321/XXXX and encoding: latin1`

**Comment by chaozmc** [comment]
Hi, 

welche Software Version vom Touch Interface hast du im Einsatz? Und hast du die Version aus dem Main oder dem v3-Branch benutzt? Wie sehen die Objekte aus die er angelegt hat? Direkt unterhalb der Instanz und dann 1 2 3 usw. oder unterhalb von den normalerweise angelegten Foldern (System, HK, WW, ...)?

Danke & Lg
