### ISSUE TITLE
Objects with max null value

### ISSUE THREAD

**Issue by looxer01** [iobroker-community-adapters/ioBroker.oekofen-json#8]
Hi,
I have received the following messages when running the adapter

oekofen-json.0 | 2022-07-20 07:12:20.125 | warn | State value to set for "oekofen-json.0.pe1.L_resttimeburner" has value "78" greater than max "null"
oekofen-json.0 | 2022-07-20 07:12:20.125 | warn | State value to set for "oekofen-json.0.pe1.L_runtimeburner" has value "179.4" greater than max "null"

the object is set to max null but receiving higher values

I am using the latest Branch

Looxer

**Comment by chaozmc** [comment]
Hi @looxer01 thanks for pointing that out.
It should work now; The conversion to number caused null values instead of undefined.

**Comment by looxer01** [comment]
Thank you. Looks good so far
